### ISSUE TITLE
Badges?

### ISSUE THREAD

**Issue by dwf** [mila-iqia/picklable-itertools#51]
Don't know how to get the badges in README.rst back to normal.

**Comment by bartvm** [comment]
Travis came back online after disabling/re-enabling. I added the repo in Scrutinizer, so that's back too. Just need to add things back in Coveralls, but they've been having issues the last two days (http://status.coveralls.io/)

**Comment by dwf** [comment]
Alright, Coveralls will come back when it comes back.
